environment:
  DOCKER_USER_NAME: ENCRYPTED[7c5a78853ea1935732ac433658e9aca5c0684f3de5bbc86a3e17727c10c4f0710d8ef04f9615bf8c49c1410810c81424]
  DOCKER_PASSWORD: ENCRYPTED[72f475b1473716f865ada3372c76172ed700ceda9724d29016b387f292efb0db3440abce4e59a169b5d014d541b69821]

timeout_in: 2h

windows_docker_builder:
  platform: windows
  os_version: 2019
  env:
    COMPUTE_ENGINE_IMAGE_NAME: windows-docker-builder-v20200813
  pull_script: docker pull mcr.microsoft.com/windows/servercore:ltsc2019
  build_core_script: docker build -m 2GB --tag k0ekk0ek/windowsservercore:2019 windowsservercore
  build_cmake_script: docker build -m 2GB --tag k0ekk0ek/windowsservercore:cmake contrib/cmake
  push_script: push_docker.bat
